#set document(
  title: "AlphaChess: Method and Implementation",
  author: "Yuri Turygin",
)
#set page(
  paper: "a4",
  margin: (x: 2.4cm, y: 2.6cm),
  numbering: "1",
  number-align: center,
)
#set text(font: ("Libertinus Serif",), size: 10.5pt, lang: "en")
#set par(justify: true, leading: 0.62em)
#show raw: set text(font: ("DejaVu Sans Mono",), size: 8.7pt)
#show heading: set block(above: 1.5em, below: 0.85em)
#set heading(numbering: "1.1")

#let accent = rgb("#1f5f8b")
#show heading.where(level: 1): it => [
  #set text(fill: accent, size: 15pt, weight: "bold")
  #block(it)
]
#show heading.where(level: 2): set text(size: 12pt, weight: "bold")
#show heading.where(level: 3): set text(size: 10.8pt, weight: "bold", style: "italic")
#show link: set text(fill: accent)

#let note(body) = block(
  fill: rgb("#f2f6f9"), stroke: (left: 2.5pt + accent),
  inset: (x: 10pt, y: 8pt), radius: 2pt, width: 100%, body,
)

// ------------------------------------------------------------------ title
#align(center)[
  #v(1.2cm)
  #text(size: 24pt, weight: "bold", fill: accent)[AlphaChess]
  #v(0.15cm)
  #text(size: 13.5pt)[How the model works, and how it is trained]
  #v(0.7cm)
  #text(size: 10pt, style: "italic")[
    A self-play chess engine in the AlphaZero family \
    PyTorch · python-chess · a native C search core
  ]
  #v(0.35cm)
  #text(size: 9pt, fill: luma(100))[Technical documentation for the `alpha_chess` repository]
]

#v(0.8cm)

#note[
  *Scope.* This document describes the method as it is actually implemented in
  this repository, with the file and function names to match. Where the
  implementation departs from the AlphaZero paper --- and it does, in several
  places that matter for running on one GPU --- the departure is called out and
  justified. Numbers quoted as measurements were measured on the target host
  (RTX 3090, 8-core/16-thread i9-11900KF).
]

#v(0.5cm)
#outline(depth: 2, indent: 1em)
#pagebreak()

// ------------------------------------------------------------------ overview
= Overview

AlphaChess learns to play chess from nothing but the rules. There is no opening
book, no endgame tablebase, no handcrafted evaluation function, and no database
of human games. A single neural network is trained against data generated by
searching with an earlier version of itself, and the only external signal in the
entire pipeline is the result of a finished game: win, loss, or draw.

The method is a loop with two halves.

#v(0.3em)
#align(center, block(
  stroke: 0.6pt + luma(160), radius: 3pt, inset: 12pt, width: 92%,
)[
  #set text(size: 9.5pt)
  #grid(
    columns: (1fr, auto, 1fr),
    align: horizon + center,
    gutter: 8pt,
    block(fill: rgb("#eef4f8"), inset: 9pt, radius: 3pt, width: 100%)[
      *Self-play* \
      #text(size: 8.7pt)[
        Play thousands of games against yourself. Every move is chosen by a
        PUCT tree search guided by the current network. Record, for each
        searched position, the search's move distribution and (once the game
        ends) its outcome.
      ]
    ],
    text(size: 16pt)[→],
    block(fill: rgb("#eef4f8"), inset: 9pt, radius: 3pt, width: 100%)[
      *Learning* \
      #text(size: 8.7pt)[
        Fit the network to that data: its policy head towards the search's
        move distribution, its value head towards the game's outcome. Write
        the new weights; the next iteration of self-play uses them.
      ]
    ],
  )
  #v(6pt)
  #text(size: 8.7pt, style: "italic")[
    Each pass is one #emph[iteration]. The network that generates the data is
    always the newest one, so the data improves as the network does.
  ]
])
#v(0.3em)

The engine of improvement is that *search is stronger than the network alone*.
A network evaluated once on a position gives a decent guess at the best move; a
few hundred simulations of tree search using that same network gives a better
one. Training the raw network to imitate its own searched output therefore
moves it towards something it could not yet produce directly --- and the next
search, now guided by a better network, is better still. This is policy
iteration, with a neural network as the function approximator and MCTS as the
policy improvement operator.

== What is in this repository

#table(
  columns: (auto, 1fr),
  stroke: none,
  inset: (x: 6pt, y: 4.5pt),
  fill: (_, y) => if calc.odd(y) { rgb("#f6f8fa") },
  [`encoding.py`], [board → tensor, and move ↔ policy index],
  [`network.py`], [the residual policy/value network],
  [`mcts.py`], [interactive PUCT search (one position at a time)],
  [`native/`], [the C search core: bitboards, movegen, encoding, PUCT trees],
  [`native_selfplay.py`], [pooled self-play driving that core],
  [`batched_selfplay.py`], [the pure-Python self-play fallback],
  [`train.py`], [the self-play → learning loop],
  [`evaluate.py`], [strength measurement against baselines and UCI engines],
  [`gui.py`, `agent.py`, `cli.py`], [playing interfaces],
)

The split between `mcts.py` and the native core is worth understanding early,
because the two searches serve different masters. The interactive search
optimises *latency*: one position, answer as fast as possible. Self-play
optimises *throughput*: thousands of games at once, and no single game cares how
long it waits. They implement the same algorithm and are tested against each
other, but almost none of the code is shared.

#pagebreak()

// ------------------------------------------------------------------ input
= Board representation

The network sees a position as a stack of $21$ binary-or-scalar planes of shape
$8 times 8$, i.e. a tensor of shape $(21, 8, 8)$. This is built by
`encode_board()` in `encoding.py`.

== Side-to-move relative orientation

The single most important property of the encoding is that it is *relative to
the side to move*, not absolute. When Black is to move, the board is flipped
vertically and the piece planes are swapped so that "our pieces" always occupy
planes 0--5 and always advance towards increasing rank.

The reason is sample efficiency. Chess is very nearly symmetric under colour
reversal: a position and its mirror have the same evaluation with the sign
flipped, and the same best move reflected. An absolute encoding forces the
network to learn every motif twice --- once for White, once for Black --- from
disjoint halves of the data. A relative encoding lets a single set of filters
serve both, so every training example teaches both colours at once.

#note[
  The flip is an implementation detail *contained inside* `encoding.py`.
  `encode_board()`, `move_to_index()` and `index_to_move()` all take the board
  and apply or undo the orientation themselves, so every caller works in
  ordinary absolute `chess` coordinates. Nothing outside this module has to
  know the network sees a flipped world.
]

The flip itself is a single `arr[:, ::-1, :]` on the assembled stack. Planes
that are spatially constant (the castling flags, the halfmove clock, the
repetition indicators, the ones plane) are unaffected by a vertical flip, so
flipping everything at once is safe and costs one array copy.

== The 21 planes

#table(
  columns: (auto, auto, 1fr),
  stroke: 0.4pt + luma(200),
  inset: (x: 6pt, y: 4.5pt),
  align: (center, center, left),
  table.header(
    [*Planes*], [*Values*], [*Contents*],
  ),
  [0--5], [$0/1$], [Our pawns, knights, bishops, rooks, queens, king],
  [6--11], [$0/1$], [Their pawns, knights, bishops, rooks, queens, king],
  [12], [$0/1$], [Our kingside castling right (broadcast over the plane)],
  [13], [$0/1$], [Our queenside castling right],
  [14], [$0/1$], [Their kingside castling right],
  [15], [$0/1$], [Their queenside castling right],
  [16], [$0/1$], [En-passant target square (a single set square, or empty)],
  [17], [$[0,1]$], [Halfmove clock $div 100$, clipped --- progress toward the fifty-move draw],
  [18], [$0/1$], [This position has occurred at least once before],
  [19], [$0/1$], [This position has occurred at least twice before],
  [20], [$1$], [Constant ones],
)

Three of these deserve comment.

*Planes 18--19 make the state Markovian.* Chess as usually stated is not a
Markov decision process on the board alone: the legality of a draw claim, and
therefore the true value of a position, depends on history. Without repetition
planes the network is asked to evaluate positions whose value it cannot
determine from its input, and a search that finds a repetition has no way to
tell the network that a draw is now available. Two planes are enough to
distinguish "new", "seen once" and "seen twice" (the third occurrence being a
claimable draw).

*Plane 20 lets padded convolutions find the edge.* A $3 times 3$ convolution
with zero padding cannot, by itself, distinguish "the board ends here" from
"there are no pieces here". A constant plane of ones gives the filters a signal
that is $1$ inside the board and $0$ in the padding, which makes edge and corner
effects --- rook mobility, king safety on the back rank --- learnable.

*The piece planes are built from bitboards, not a loop.* `_piece_planes()` takes
python-chess's twelve 64-bit masks, concatenates them into 96 little-endian
bytes, and expands them with a single `numpy.unpackbits` call. Bit $i$ of a mask
is square $i$, so the unpacked bits reshape directly to
`[plane, rank, file]`. This replaces a Python loop over `board.piece_map()` and
is the difference between encoding being a rounding error and being a
bottleneck.

== Storage packing

Stored in float32, one position is $21 times 64 times 4 = 5.4$ KB, and a replay
buffer of two million positions would be 10.8 GB of states alone. Every value in
the encoding is either binary or a scaled small rational, so `pack_state()`
quantises to `uint8` and `unpack_state()` restores:

$ "packed" = "round"(x dot 255), quad x = "packed" / 255 $

This is lossless for the binary planes and costs at most $1/255$ of precision on
plane 17, which is itself only a coarse progress indicator. The cost is 1.3 KB
per position instead of 5.4 KB.

#pagebreak()

// ------------------------------------------------------------------ moves
= Move representation

The policy head emits a fixed vector of $4672$ logits. That number is
$64 times 73$: for each of the 64 *origin* squares, 73 possible *move types*.
This is the AlphaZero move encoding, and it is chosen so that a move's index
depends on geometry rather than on the particular position --- the same index
means the same thing everywhere on the board.

$ "index"(m) = "from" times 73 + "plane"(m) $

== The 73 planes

#table(
  columns: (auto, auto, 1fr),
  stroke: 0.4pt + luma(200),
  inset: (x: 6pt, y: 4.5pt),
  align: (center, center, left),
  table.header([*Planes*], [*Count*], [*Move type*]),
  [0--55], [56], [
    Queen-like slides: 8 directions (N, NE, E, SE, S, SW, W, NW) × 7 distances
    (1--7). Plane $= d times 7 + (n - 1)$.
  ],
  [56--63], [8], [Knight jumps, one plane per offset.],
  [64--72], [9], [
    Underpromotions: 3 file deltas (left, straight, right) × 3 pieces
    (knight, bishop, rook).
  ],
)

Everything that is not a knight jump or an underpromotion is a queen-like slide,
including king moves (distance 1), *castling* (encoded as the king's two-square
move), *en passant* (a diagonal pawn slide), and *queen promotion* (a pawn's
one-square advance or capture onto the back rank). Queen promotion needs no
plane of its own because a pawn reaching the back rank can only promote, and
promoting to a queen is the overwhelming default; the three underpromotion
planes exist precisely because that default is occasionally wrong.

== Orientation, again

`move_to_index()` applies the same vertical flip as the encoder before computing
the index:

```python
if board.turn != chess.WHITE:
    from_sq ^= 56          # rank r -> rank 7-r, file unchanged
    to_sq   ^= 56
```

The `^ 56` trick works because a square index is `rank * 8 + file`, so XOR-ing
the top three bits with `111` maps rank $r$ to rank $7-r$ and leaves the file
alone. The consequence is the one that matters: *a position and its colour
mirror map corresponding moves to identical policy indices*, so the policy head
shares all its learning across colours exactly as the board encoding does.

== Coverage

The encoding is not obviously complete, and `test_encoding.py` checks that it is:
every legal move, across openings, random playouts, promotions, underpromotions,
castling and en passant, must survive a round trip through `move_to_index()` and
`index_to_move()`. Of the 4672 slots, a large fraction are never legal from any
position (a knight jumping off the board, a promotion from the middle of the
board); these simply never receive prior mass, because the search masks the
policy to the legal moves before using it.

#pagebreak()

// ------------------------------------------------------------------ network
= The network

`AlphaZeroNet` in `network.py` is a standard AlphaZero-style residual tower with
two heads. It maps a batch of encoded boards to a policy and a value:

$ f_theta : (B, 21, 8, 8) arrow.r ( underbrace((B, 4672), "policy logits"), underbrace((B, 1), "value") ) $

== Architecture

#table(
  columns: (auto, 1fr),
  stroke: 0.4pt + luma(200),
  inset: (x: 7pt, y: 5pt),
  table.header([*Stage*], [*Layers*]),
  [Stem],
  [`Conv2d(21 → C, 3×3, pad 1, no bias)` → `BatchNorm2d` → `ReLU`],
  [Residual tower],
  [
    $B$ blocks, each: `Conv3×3 → BN → ReLU → Conv3×3 → BN`, then add the block
    input and `ReLU`. Channels stay at $C$ and the spatial size stays $8 times 8$
    throughout --- there is no pooling or striding anywhere in the network.
  ],
  [Policy head],
  [`Conv2d(C → 32, 1×1)` → `BN` → `ReLU` → flatten (2048) → `Linear(2048 → 4672)`],
  [Value head],
  [
    `Conv2d(C → 32, 1×1)` → `BN` → `ReLU` → flatten (2048) →
    `Linear(2048 → 64)` → `ReLU` → `Linear(64 → 1)` → `tanh`
  ],
)

The defaults are $C = 128$ channels and $B = 10$ blocks. No spatial
downsampling is used because the board is already tiny: an $8 times 8$ grid
after ten $3 times 3$ convolutions has a receptive field covering the whole
board several times over, and pooling would only discard the square-level
detail the policy head needs.

The value head's `tanh` bounds the output to $[-1, +1]$, matching the game
outcomes it is trained against: $+1$ win, $0$ draw, $-1$ loss, always *from the
perspective of the side to move*.

== Parameter budget

#table(
  columns: (1fr, auto, auto),
  stroke: 0.4pt + luma(200),
  inset: (x: 7pt, y: 4.5pt),
  align: (left, right, right),
  table.header([*Component* (at $C=128$, $B=10$)], [*Parameters*], [*Share*]),
  [Stem], [24,448], [0.2%],
  [Residual tower (10 blocks)], [2,954,240], [23.3%],
  [Policy head], [9,577,088], [75.5%],
  [Value head], [135,361], [1.1%],
  table.hline(stroke: 0.6pt),
  [*Total*], [*12,691,137*], [100%],
)

Three quarters of the model is the policy head's final linear layer, a dense
$2048 times 4672$ matrix. This is a known and slightly awkward property of the
AlphaZero move encoding: the output space is large and mostly unreachable, and a
fully-connected projection into it dominates the parameter count while the
convolutional tower --- where the chess understanding actually lives --- is a
quarter of the weights. It is left as-is here because it matches the reference
method and because parameters are not the binding constraint; *throughput* is.

For scale, at other sizes: $96 times 8$ is 11.1M parameters, $128 times 10$ is
12.7M, $160 times 12$ is 15.3M. The tower grows quadratically in $C$ while the
policy head grows linearly, so the ratio improves as the network widens.

== Why network size sets self-play speed

Once the search itself is fast (§6.5), the GPU forward pass is the bottleneck of
the entire pipeline, and network size translates directly into games per hour.
Measured at batch 1024 on a 3090: $96 times 8$ runs at $tilde.op 207$k
positions/s, $128 times 10$ at $tilde.op 121$k, $160 times 12$ at
$tilde.op 65$k. A smaller network buys data volume at the cost of ceiling. The
$128 times 10$ default is the balance point chosen for the repository's
1500--2000 Elo target.

#pagebreak()

// ------------------------------------------------------------------ search
= Search: PUCT Monte-Carlo tree search

The network alone is a move-ordering heuristic and a static evaluator. What
actually plays chess --- and what generates the training targets --- is a
best-first tree search that uses the network to decide where to look.

== What a node stores

Each edge $(s, a)$ from a node holds four statistics, all from the perspective
of *the player to move at $s$*:

#table(
  columns: (auto, 1fr),
  stroke: none,
  inset: (x: 6pt, y: 3.5pt),
  fill: (_, y) => if calc.odd(y) { rgb("#f6f8fa") },
  [$N(s,a)$], [visit count --- how many simulations went through this edge],
  [$W(s,a)$], [total action value --- the sum of every value backed up through it],
  [$Q(s,a)$], [mean action value, $W \/ N$],
  [$P(s,a)$], [prior probability, from the network's policy at $s$],
)

== The selection rule

At every node on the way down, the search takes the child maximising

$ a^* = op("argmax")_a [ Q(s,a) + c_"puct" dot P(s,a) dot frac(sqrt(sum_b N(s,b)), 1 + N(s,a)) ] $

with $c_"puct" = 1.5$ by default. The two terms trade off directly:

- $Q(s,a)$ is *exploitation* --- what the search has learned this move is worth.
- The second term is *exploration*, large for moves the network likes ($P$ high)
  and for moves that have not been tried ($N$ small), and it shrinks as
  $1 \/ (1 + N)$ once a move starts getting visits. The $sqrt(sum_b N)$ factor
  keeps exploration alive as the node's total visit count grows, rather than
  letting the first promising move monopolise the budget.

On the very first descent through a node, $sum_b N(s,b) = 0$, the exploration
term vanishes for every child, and the prior alone decides --- the search's
first guess is exactly the network's.

== A simulation

Each simulation is four phases:

+ *Select.* From the root, apply the PUCT rule repeatedly until reaching a node
  that has not been expanded, pushing each move onto a scratch board as you go.
+ *Evaluate.* Run the network on the leaf. Mask its policy logits to the legal
  moves, softmax over just those, and use the result as the priors $P$ of the
  new edges. The value head gives $v$, the leaf's evaluation from the leaf
  player's point of view.
+ *Expand.* Create the leaf's children with those priors and $N = W = Q = 0$.
+ *Back up.* Walk the path back to the root, and at each step *negate the value*
  before accumulating it: $ N arrow.l N + 1, quad W arrow.l W + v, quad Q arrow.l W \/ N $
  The negation is what makes this work for a two-player zero-sum game --- a
  position that is good for the mover is exactly as bad for the opponent who
  chose the move leading into it.

== Terminal positions

A node that is checkmate, stalemate, insufficient material, fifty-move or a
threefold repetition has a value that is *known*, not estimated, and the network
must not be consulted for it. Both searches resolve this once, when the node is
first reached, and cache the result on the node (`terminal_value`).

This is a deliberate performance decision as much as a correctness one. Calling
python-chess's `is_game_over(claim_draw=True)` at every node of every descent
costs roughly 164 µs --- utterly dominating a search whose whole point is to run
hundreds of simulations per move. Resolving it once per node, at the leaf, and
reusing the cached answer on every subsequent visit removes that cost.
`test_mcts.py` and `test_selfplay.py` both pin the fast path to python-chess's
`claim_draw` semantics across all five ways a game can end.

== Root Dirichlet noise

A search that always follows the network's priors can never discover that the
network is wrong. At the root of a self-play search --- and *only* there, and
only during self-play --- the priors are mixed with Dirichlet noise:

$ P'(s_0, a) = (1 - epsilon) P(s_0, a) + epsilon eta_a, quad eta tilde "Dir"(alpha) $

with $alpha = 0.3$ and $epsilon = 0.25$. This guarantees that every root move
gets some prior mass and so has a chance of being explored, which is the
mechanism by which self-play data can contain moves the current network would
never play. Evaluation and interactive play add no noise: there, you want the
engine's best judgement, not exploration.

== First-play urgency

The native search adds an option the Python one does not have. In the rule
above, an unvisited child has no $Q$, and the implementation must supply one.
The plain choice --- and what `mcts.py` does --- is $Q = 0$, i.e. "assume a
draw".

With `--fpu-reduction` set, the native core instead gives unvisited children the
parent's own value, discounted by how much prior mass has already been explored:

$ Q_"fpu" = Q_"parent" - r dot sqrt(sum_(a : N(s,a) > 0) P(s,a)) $

The intuition: if the search has already looked at most of the plausible moves
and found the position good, an untried move is probably also roughly that good
(so inheriting $Q_"parent"$ beats assuming a draw), but the more has already
been explored without finding better, the less likely an untried move is to be
an improvement (so the penalty grows). Setting $r = 0$ recovers the flat-zero
behaviour exactly, which is the default.

== Subtree reuse

When a move is played, the subtree under it is not thrown away --- it becomes
the new root, keeping its visit counts and values. The work spent evaluating the
opponent's likely replies is work that does not have to be repeated.

In the native core this is `arena_copy_subtree()`, which copies the chosen
child's subtree into a freshly reset arena rather than maintaining a free list.
With an untrained network the saving is small (the visit distribution is nearly
flat, so 179 of 200 simulations per ply are still new work), but it grows
substantially as the network sharpens and the search starts concentrating its
visits.

== Choosing the move

After the simulation budget is spent, the move is chosen from the root's *visit
counts*, not from $Q$ and not from the network's policy. Visit counts are the
search's real output: PUCT allocates visits to moves in proportion to how good
they keep looking under repeated examination, which makes $N$ a lower-variance
signal than any single node's $Q$.

During the first `--temperature-moves` plies (default 30) of a self-play game,
the move is *sampled* in proportion to visit count:

$ pi(a) = frac(N(s_0, a), sum_b N(s_0, b)) $

After that, and always during evaluation, the most-visited move is played
deterministically. The early sampling is what makes self-play games diverge from
one another; without it, a deterministic engine against itself would play the
same game every time and the replay buffer would contain one position per ply
for the entire run.

#pagebreak()

// ------------------------------------------------------------------ selfplay
= Self-play

Self-play is the wall-clock bottleneck of the whole method, and most of this
repository's engineering is here. The naive implementation --- one game, one
simulation at a time, one position per forward pass --- leaves a modern GPU
about 99% idle.

== Batching: one leaf per game per step

The structural trick is to run many games *concurrently* and interleave their
searches. Each game advances its own tree by exactly one simulation per step,
and every game's leaf position for that step is collected into a single batch:

#align(center, block(stroke: 0.6pt + luma(160), radius: 3pt, inset: 11pt, width: 92%)[
  #set text(size: 9.3pt)
  #set par(justify: false)
  *for each step:* \
  #h(1em) 1. for every active game: descend its tree to a leaf (CPU) \
  #h(1em) 2. stack all those leaves into one $(G, 21, 8, 8)$ batch \
  #h(1em) 3. one forward pass (GPU) \
  #h(1em) 4. for every game: expand its leaf and back up (CPU) \
  #h(1em) 5. any game whose budget is spent plays its move and may finish
])

With `--games-in-flight 1024`, the network sees batches of about a thousand
positions instead of one. Since a GPU's throughput at batch 1 and at batch 1024
differ by orders of magnitude, this single change is most of the speedup: a
$128 times 10$ network runs at $tilde.op 94$k positions/s at batch 512,
$tilde.op 121$k at 1024, and $tilde.op 127$k at 2048.

The cost is memory: each in-flight game holds its own search tree and its own
accumulated training examples, so `--games-in-flight` is bounded by host RAM.

== Pools: overlapping CPU and GPU

Batching alone still alternates: the CPU descends while the GPU idles, then the
GPU computes while the CPU idles. `--pools` runs several independent groups of
games so that one pool's tree search overlaps the next pool's forward pass.

Two pools suffice in principle; three is the default because it also absorbs the
jitter from a pool that momentarily has few active games. More than three just
fragments the batches. The knob interacts with `--games-per-iter`: a pool refills
a finished game with a fresh one until its quota is exhausted, after which the
batch decays as the last games drain, so keeping games-per-iter well above
$"pools" times "games-in-flight"$ (16000 vs 3072 in the default recipe) keeps
that tail a small share of the iteration.

== Playout-cap randomisation

Most of a game's search budget buys very little. The position is not close, and
a 200-simulation search picks the move a 50-simulation search would. Playout-cap
randomisation --- from KataGo #footnote[Wu, D. J. (2019). #emph[Accelerating
Self-Play Learning in Go].] --- exploits this asymmetry between the two things a
self-play game produces.

A game produces *policy targets* (one per searched ply, and only worth recording
if the search was strong) and *one value target* (the game's result, which is
worth exactly as much regardless of how carefully the moves were chosen). So:

#table(
  columns: (auto, 1fr),
  stroke: 0.4pt + luma(200),
  inset: (x: 7pt, y: 5pt),
  table.header([*Ply type*], [*Treatment*]),
  [Full (probability `--full-search-prob`, default 0.25)],
  [
    Full `--simulations` budget, root Dirichlet noise, *and* the resulting
    visit distribution is recorded as a training example.
  ],
  [Fast (the other 75%)],
  [
    Only `--fast-simulations` (default 50), no noise, *no training example
    recorded*. These plies exist purely to move the game along to a result.
  ],
)

Measured over 400 complete games, this takes a ply from 179 evaluated positions
to 77 --- so the same GPU-hour finishes *2.2× as many games*, and therefore 2.2×
as many game outcomes to learn a value function from, while every policy target
it records still comes from a full-strength search. Subtree reuse compounds it:
a fast ply often already has more carried-over visits than its budget calls for,
and costs a single simulation.

The accounting consequence is that an iteration records roughly 4× fewer
positions per game, which the `--sample-reuse` rule (§7.4) accounts for
automatically.

== Resignation

Playing out a hopeless position to checkmate is wasted GPU time. When the
mover's best root value stays at or below `--resign-threshold` (default $-0.90$)
for two consecutive plies, the game is resigned and scored as a loss.

The danger is obvious: a resignation threshold that is too aggressive
mislabels positions that were actually saveable, and poisons the value target.
So a fraction of games --- `--resign-disable-fraction`, default 10% --- is
played out with resignation *suppressed*, purely so the engine can measure how
often it *would* have resigned a game it went on to draw or win. That
false-positive rate is printed every iteration. If it climbs above about 5%, the
threshold is too loose and should be lowered.

== The native search core

Profiling the pure-Python engine put the time as follows:

#table(
  columns: (1fr, auto),
  stroke: 0.4pt + luma(200),
  inset: (x: 7pt, y: 4.5pt),
  align: (left, right),
  table.header([*Where self-play time went (Python engine)*], [*Share*]),
  [python-chess legal move generation], [$tilde.op$40%],
  [Move → policy index], [$tilde.op$14%],
  [Board → tensor encoding], [$tilde.op$10%],
  [Tree descent (push, PUCT select, backup)], [$tilde.op$17%],
)

None of that is GPU work. All of it is Python doing bookkeeping, and the card
sat idle waiting for it. So the board, move generation, the encoding and the
PUCT tree were all moved into a small C extension (`alpha_chess/native/`):

#table(
  columns: (auto, 1fr),
  stroke: none,
  inset: (x: 6pt, y: 4pt),
  fill: (_, y) => if calc.odd(y) { rgb("#f6f8fa") },
  [`bitboard.h`], [attack tables and runtime-generated magic bitboards],
  [`position.h`], [position, Zobrist hashing, make-move, legal move generation],
  [`encode.h`], [the 21-plane encoding and 4672-way index, matching `encoding.py`],
  [`mcts.h`], [arena-allocated PUCT trees and the self-play game driver],
  [`fastchess.c`], [CPython bindings; releases the GIL for the whole search step],
)

The extension is compiled on first use --- `native.py` tries `cc`, `gcc`,
`clang`, then the pip-installed `ziglang` --- so no system compiler and no build
step is required of the user, and a host without one silently falls back to the
Python engine.

#note[
  *Result.* $tilde.op 102$k evaluated positions/s against $tilde.op 27$k for the
  pure-Python engine on the same hardware: *3.8× the raw search throughput*, and
  with playout caps, *8.5× the games per hour*. The bottleneck moves off the CPU
  and onto the GPU, which is where it should be --- the card now runs at its
  power limit. A week-long run becomes a long weekend.
]

The obligation this creates is correctness: a second chess implementation is a
second chance to be subtly wrong. `test_native.py` runs *perft* on the six
standard positions (\~194M nodes between them, covering castling, en passant,
promotion, discovered check, pins and stalemate) and diffs the native legal-move
set, move-to-index mapping and encoded planes against python-chess and
`encoding.py` over thousands of positions from random games --- including
en-passant positions specifically, the one feature where the two encoders could
plausibly disagree.

#pagebreak()

// ------------------------------------------------------------------ training
= Training

== The targets

Every recorded example is a triple $(s, pi, z)$:

#table(
  columns: (auto, 1fr),
  stroke: none,
  inset: (x: 6pt, y: 5pt),
  fill: (_, y) => if calc.odd(y) { rgb("#f6f8fa") },
  [$s$],
  [the encoded position, `uint8`-packed],
  [$pi$],
  [
    the search's normalised root visit distribution at that position ---
    the *policy* target
  ],
  [$z$],
  [
    the game's eventual result, $+1 \/ 0 \/ -1$, *from the perspective of the
    player to move at $s$* --- the *value* target
  ],
)

The sign convention on $z$ is the detail that is easy to get wrong. The game
produces one White-relative result; each example then flips it according to
whose turn it was at that position (`out_values[o] = turn ? result : -result`).
This has to match the value head's convention --- side-to-move relative, like
the encoding --- or the network learns the negation of chess.

Note what is *not* in the target. There is no per-move evaluation, no engine
annotation, no search score. The value target is the raw, extremely noisy
outcome of one game. Its saving grace is that it is unbiased: averaged over
enough games from similar positions, it converges on the true value, and the
network's job is precisely to do that averaging.

== The loss

$ cal(L) = underbrace(-sum_a pi(a) log p_theta (a | s), "policy: cross-entropy") + underbrace((z - v_theta (s))^2, "value: squared error") + underbrace(lambda norm(theta)^2, "weight decay") $

The policy term is a cross-entropy between the search distribution and the
network's softmax, which pulls the raw network towards what the search
concluded. The value term is a plain MSE against the game result. Weight decay
($10^(-4)$) is applied by the optimizer rather than added explicitly.

The two terms are summed with *equal weight*. There is no tuning constant
between them, matching AlphaZero; the value loss is naturally smaller in
magnitude and the policy term dominates the gradient early in training.

*The policy target is sparse.* A 4672-wide dense float32 target per example
would be 18.7 KB, most of it zeros --- only the moves that actually received
visits are non-zero, at most `MAX_POLICY_TARGETS = 80` of them. So the buffer
stores `(index, value)` pairs and the loss gathers rather than materialising the
dense row:

```python
log_probs = F.log_softmax(policy_logits, dim=1)
picked = log_probs.gather(1, pol_idx)        # (B, 80)
policy_loss = -(pol_val * picked).sum(dim=1).mean()
```

Padded slots carry value $0$ and so contribute nothing. This is mathematically
identical to the dense cross-entropy and vastly cheaper in both memory and
bandwidth.

== The replay buffer

A fixed-capacity ring of examples (`ReplayBuffer` in `self_play.py`), default
two million positions. Training samples uniformly from it, so each iteration
learns from a *window of recent history* rather than only the games just
generated --- which decorrelates consecutive gradient steps and stops the
network chasing the idiosyncrasies of one batch of games.

The storage is column-oriented and deliberately compact, because buffer size is
one of the levers on final strength and a dense buffer runs out of RAM long
before it runs out of usefulness:

#table(
  columns: (1fr, auto, auto),
  stroke: 0.4pt + luma(200),
  inset: (x: 7pt, y: 4.5pt),
  align: (left, right, right),
  table.header([*Per position*], [*Dense*], [*As stored*]),
  [State], [5.4 KB], [1.3 KB (`uint8`)],
  [Policy target], [18.7 KB], [$tilde.op$0.6 KB (sparse, ≤80 pairs)],
  [Value], [4 B], [4 B],
  table.hline(stroke: 0.6pt),
  [*Total*], [$tilde.op$*21 KB*], [$tilde.op$*1.9 KB*],
)

At 1.9 KB per position, two million positions cost about 3.8 GB --- feasible on
a workstation. Dense, the same buffer would be 42 GB. Appends are vectorised
ring writes and sampling is a single fancy-index gather, both $O("batch")$.

The buffer is persisted alongside `train_state.pt` (unless `--no-save-buffer`),
so a resumed run keeps its history instead of restarting from an empty window.

== How many gradient steps

The number of optimizer steps per iteration is set by `--sample-reuse` (default
4.0) rather than by the buffer size:

$ "steps" = frac("new positions" times "sample-reuse", "batch size") $

The name is literal. A position survives
$"buffer-size" \/ "new positions"$ iterations before eviction, and over that
span the draws total $"buffer-size" times "sample-reuse"$ across
$"buffer-size"$ positions --- so each position is, in expectation, sampled
`sample-reuse` times over its lifetime.

The point is that the work then scales with *the data*. The older rule (one pass
over the whole buffer per epoch) scaled with the *buffer*: 7,812 steps an
iteration at a 2M buffer and batch 1024, whether that iteration produced 50k new
positions or 800k, which both wasted time and re-used each position roughly 20
times --- far more than the data supports. `--train-steps` overrides the rule
entirely when an explicit budget is wanted.

== Optimizer and schedule

#table(
  columns: (auto, 1fr),
  stroke: none,
  inset: (x: 6pt, y: 4pt),
  fill: (_, y) => if calc.odd(y) { rgb("#f6f8fa") },
  [Optimizer], [Adam, weight decay $10^(-4)$],
  [Learning rate], [
    cosine decay across the *whole run*, from `--lr` ($10^(-3)$) to `--lr-final`
    (default $"lr" times 0.1$):
    $ eta_i = eta_"final" + (eta_0 - eta_"final") dot 1/2 (1 + cos(pi i \/ N)) $
  ],
  [Gradient clipping], [global norm $1.0$],
  [Batch size], [1024],
  [Mixed precision], [fp16 autocast + `GradScaler`, CUDA only],
)

The LR schedule is indexed by *iteration*, not by gradient step, so it is tied
to `--iterations`. Resuming with a larger `--iterations` therefore stretches the
remaining schedule rather than restarting it.

On CUDA the loop additionally enables `cudnn.benchmark`, moves the model to
`channels_last`, and copies host→device from pinned memory with
`non_blocking=True`. Every one of these is guarded: on CPU and Apple-Silicon MPS
they are skipped and everything runs in fp32, which is the path the test suite
uses.

== Checkpoints and resuming

Every iteration writes `best.pt` (weights plus the architecture config, so any
size reloads correctly) and `train_state.pt` (model, optimizer, iteration
counter, learning rate, and the Python/NumPy/Torch/CUDA RNG states). Numbered
`checkpoint_NNN.pt` files are kept every `--checkpoint-every` iterations.

`--resume` pointed at a directory or a `train_state.pt` restores all of that
*and* the replay buffer, and continues from the next iteration. Pointed at a
plain model checkpoint instead, it loads weights only and starts a fresh
optimizer --- useful for fine-tuning. Missing optimizer state never crashes the
run.

#pagebreak()

// ------------------------------------------------------------------ eval
= Measuring strength

`evaluate.py` plays a checkpoint against an opponent over a series of games with
alternating colours and reports W/D/L, score, and an Elo difference:

$ Delta"Elo" = -400 log_10 (1/S - 1) $

where $S$ is the score in $[0, 1]$, clamped at $1 \/ (2 n)$ so a whitewash gives
a finite estimate that tightens as the match lengthens.

#table(
  columns: (auto, 1fr),
  stroke: 0.4pt + luma(200),
  inset: (x: 7pt, y: 4.5pt),
  table.header([*Opponent*], [*What it tells you*]),
  [`random`], [Sanity only. Any trained network should crush it.],
  [`material`], [A greedy material-counting baseline. The first real rung.],
  [`model:PATH`], [Another checkpoint of your own --- measures *improvement*.],
  [`uci:PATH`], [An external engine (e.g. Stockfish) --- the only path to a comparable number.],
)

#note[
  *The Elo number is relative to the opponent, not absolute.* Beating `material`
  by 300 points says nothing about FIDE rating. Only a calibrated external
  engine anchors a comparable figure --- and even then, note that engines
  enforce a floor on strength limiting (Stockfish 16's `UCI_Elo` will not go
  below 1320; below that, use `--uci-skill`, which reaches Skill Level 0), and
  that a strength-limited engine is not a human of the same nominal rating. It
  plays weaker moves but still never hangs a piece.
]

Games are decorrelated by `--opening-plies` random opening moves per
colour-swapped pair, so two deterministic players still produce varied games
rather than repeating one line.

= Hyperparameter reference

The defaults below are the RTX 3090 recipe from the README.

#table(
  columns: (auto, auto, 1fr),
  stroke: 0.4pt + luma(200),
  inset: (x: 6pt, y: 4pt),
  align: (left, center, left),
  table.header([*Flag*], [*Default*], [*Role*]),
  [`--iterations`], [80], [Self-play → train cycles; also the cosine LR horizon],
  [`--games-per-iter`], [16000], [Games generated per iteration],
  [`--simulations`], [200], [Budget on full-search plies],
  [`--fast-simulations`], [50], [Budget on playout-capped plies],
  [`--full-search-prob`], [0.25], [Fraction of plies searched fully and recorded],
  [`--pools`], [3], [Independent game pools, for CPU/GPU overlap],
  [`--games-in-flight`], [1024], [Concurrent games per pool = the network batch],
  [`--channels` / `--blocks`], [128 / 10], [Network width and depth],
  [`--batch-size`], [1024], [Minibatch for the gradient step],
  [`--epochs`], [4], [Optimization passes per iteration],
  [`--sample-reuse`], [4.0], [Expected samples per position per lifetime],
  [`--lr`], [$10^(-3)$], [Initial Adam LR, cosine-decayed to $10^(-4)$],
  [`--weight-decay`], [$10^(-4)$], [L2 regularisation],
  [`--grad-clip`], [1.0], [Max gradient norm],
  [`--buffer-size`], [2,000,000], [Replay capacity in positions ($tilde.op$3.8 GB)],
  [`--temperature-moves`], [30], [Plies sampled from visit counts before going greedy],
  [`--max-moves`], [400], [Ply cap; a cut-off game is scored a draw],
  [`--resign-threshold`], [$-0.90$], [Root value at which a game is resigned],
  [`--resign-disable-fraction`], [0.10], [Games played out to measure resign false positives],
  [`--c-puct` (internal)], [1.5], [PUCT exploration constant],
  [Dirichlet $alpha$, $epsilon$], [0.3, 0.25], [Root noise shape and mixing weight],
)

= What this is and is not

This is a faithful, runnable implementation of the AlphaZero method, engineered
so that the loop closes on a single consumer GPU in days rather than on a TPU
pod in hours. The reference work used 5,000 first-generation TPUs for self-play
and 64 second-generation TPUs for training; the target here is one RTX 3090 and
a practical ceiling around 1500--2000 Elo.

Everything that makes that feasible is a throughput decision, not an algorithmic
shortcut: batching thousands of concurrent games into one forward pass, moving
the search into C so the GPU is the bottleneck, spending the search budget where
it buys game outcomes rather than uniformly, and storing the replay buffer
compactly enough that a useful window fits in RAM. The learning algorithm
itself --- PUCT with network priors, visit-count policy targets, game-outcome
value targets, and a combined cross-entropy plus MSE loss --- is unchanged.

What it is not is a promise of grandmaster strength. The scaling is real but so
is the gap: AlphaZero's published result is several orders of magnitude more
compute away.
